### ISSUE TITLE
Can't attach audio files.

### ISSUE THREAD

**Issue by DevilWarrior** [kaisellgren/mailer#66]
Hi,

After updating to 2.0.8 (from 1.1.4) and doing some refactoring in the code, everything works except sending audio files as attachments. I can send plain emails correctly, I can also send email with attached images and/or documents. I can't however send .mp4 audio files. I get the error below:

`Could not load source 'dart:core/runtime/libobject_patch.dart': <source not available>.`

Further looking into the exception, it seems as though the problem happens in line 61 of the ir_header.dart file.

```
NoSuchMethodError (NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length)
```

**Comment by close2** [comment]
version 2.1.1 does no longer crash.

The mime library is not able to identlify the content-type of your mp4 file.
The default is now to use: `application/octet-stream` for binary content.

You might want to specify the content-type with the `contentType` named argument to the attachment constructor.

**Comment by DevilWarrior** [comment]
Thanks! My bad!

**Comment by close2** [comment]
you did nothing wrong!  There was a bug!

In your case the mime library is not able to identify the content-type.  Which is unfortunate.

I imagine, that most mail programs are perfectly fine with `application/octet-stream` but if you want mailer to use the correct content type you have to specify it.
